### ISSUE TITLE
Add ability to Unsubscribe

### ISSUE THREAD

**Issue by viktor-shmigol** [troyanskiy/ng2-broadcast#2]
I mean like this 
```
this.broadcaster.unsubscribe('eventName')
```

**Comment by troyanskiy** [comment]
You should be able to unsubscribe like that
``` typescript
let mySub = this.broadcaster.on<any>
  .subscribe(message => {
    ...
  });

// unsubscribe after 5 sec
setTimeout(() => mySub.unsubscribe(), 5000);

```

**Comment by viktor-shmigol** [comment]
@troyanskiy thanks I'll try to do that. But by the way it would be great to do same like https://ionicframework.com/docs/v2/api/util/Events/

**Comment by troyanskiy** [comment]
Honestly I believe that better to avoid using that king of way of programming.
That thing brings a lot of complexity for project maintenance. It's like "rabbit hole" where you can put something and after "sometime" it will appear in some place. And here you have problems with figuring out who sent, why, who catch it...

So me myself not using that nor Ionic Event.
Так что, советую не использовать всякие бродкастеры, или использовать их в самую последнюю очередь, иначе это превратится в "broadcast hell" ;)

**Comment by viktor-shmigol** [comment]
@troyanskiy на всі сто з тобою погоджуюсь. Просто приходиться фіксить існуючий проект, де юзається твій плагін, сорі шо потурбував :+1: , будуть питання по ruby,rails,angular,js питай постараюсь допомогти

**Comment by troyanskiy** [comment]
Я приятно удивлен, что кто-то пользуется этой либой. :)
Руби и рельсы никогда не юзал...
Будут вопросы по node.js, angular2, ionic2, js, ts пиши тоже )
Хорошего вечера.

Закрываю тикет.
